#!/bin/bash

LOG_DIR=~/nginx_status_logs 
DATA_HORA=$(date '+%Y-%m-%d %H:%M:%S') 
SERVICE="Nginx" 
  
SERVICE_STATUS=$(systemctl is-active nginx)

if [ "$SERVICE_STATUS" = "active" ]; then STATUS="ONLINE" 
MENSAGEM="O serviço está rodando normalmente." echo "$DATA_HORA - $SERVICE - $STATUS - $MENSAGEM" >> $LOG_DIR/nginx_online.log 
else STATUS="OFFLINE" MENSAGEM="O serviço está offline ou inativo." 
echo "$DATA_HORA - $SERVICE - $STATUS - $MENSAGEM" >> $LOG_DIR/nginx_offline.log 

fi 
